### ISSUE TITLE
Missing Max Signal Region End Coordinate

### ISSUE THREAD

**Issue by coke6162** [FredHutch/SEACR#13]
Hi -

My lab mates and I have run into an issue where some of the maximum signal regions (Field 6) reported by SEACR lack an end coordinate. For example, here is a line in one of the files output by SEACR: 

> chr8	75582803	75585869	13496	14	chr8:75583785-

Out of 12433 peak regions in this particular file, there are 30 that lack a maximum signal region end coordinate. 

I visualized my data on UCSC at chr8:75583785-75585869 (i.e. the start coordinate of maximum signal region followed by the end coordinate of the full peak region), and nothing seemed amiss. Here is a screenshot -

<img width="711" alt="Screen Shot 2019-10-03 at 12 53 38 PM" src="https://user-images.githubusercontent.com/45079765/66155440-db84f380-e5dc-11e9-8fd0-342f86b24385.png">

Would this arise through some problem with my data, or could it be a bug?

**Comment by mpmeers** [comment]
Hi,

What you're observing is almost certainly a bug, as it's something I have seen in the past and thought I had addressed, but apparently have not. I will most likely have to tweak lines 166 and 168 in SEACR_1.1.sh, since that's the sole place where the max score line is implemented. Thanks for the catch.

I have a few updates I need to work on and have been meaning to push to a new version soon, so I'll add this to the list and update you if/when I've identified the problem so that you can give it a try and see if the issue is resolved. Thanks again.

Mike

**Comment by mpmeers** [comment]
Hi,

Im the most recent release (v1.2), I fixed a bug that should resolve the issue you described--please let me know if the issue persists and I will take another look at it.

Mike
