### ISSUE TITLE
getting different peaks between two Cut&Run analysis pipelines

### ISSUE THREAD

**Issue by lb15** [FredHutch/SEACR#3]
Hi there,

I tried running SEARC on my transcription factor Cut&Run data and IgG control. I have previously utilized the MACS2 peak caller. With the MACS2 peak caller, I find peaks that I think are real and make sense - a couple of known target genes and the top motif matches that transcription factor. When I ran the data through SEARC, I could no longer find these peaks and the called peaks do not overlap with the previous peaks, by looking through the genome browser. I think I must be preparing the files incorrectly to get such discordant results. Would you mind checking that my code below for preprocessing the bam file would result in appropriate input into SEARC. 

I begin with a bowtie2 aligned bam file (TF and IgG control). I have not included any normalization to the yeast spike-in. Do you have a recommendation of when to add that normalization? 

Thanks so much!
Sincerely,
Lauren

## ready for input into SEARC

bamfile=$1
output_dir=$2
output_name=$3

samtools flagstat $bamfile > $output_dir/"$output_name"_bam_flagstat.txt
samtools sort -n $bamfile > $output_dir/"$output_name"_sorted.bam
samtools fixmate $output_dir/"$output_name"_sorted.bam $output_dir/"$output_name"_sorted_fixed.bam
samtools flagstat $output_dir/"$output_name"_sorted_fixed.bam > $output_dir/"$output_name"_sorted_fixed_flagstat.txt
samtools view -bf 0x2 $output_dir/"$output_name"_sorted_fixed.bam | bedtools bamtobed -i stdin -bedpe > $output_dir/"$output_name"_properpair.bed
bedtools sort -i $output_dir/"$output_name"_properpair.bed > $output_dir/"$output_name"_properpair_sortchr.bed
awk '{ print $1"\t"$2"\t"$6}' $output_dir/"$output_name"_properpair_sortchr.bed > $output_dir/"$output_name"_properpair_sortchr_startend.bed

bedtools genomecov -bg -i $output_dir/"$output_name"_properpair_sortchr_startend.bed -g /Volumes/LB_ReiterLab/Reiter_Seq/CR11/cutruntools/assemblies/chrom.mm10/mm10.chrom.sizes > $output_dir/"$output_name"_properpair_sortchr_startend.bg

**Comment by mpmeers** [comment]
Hi Lauren,

Could you share with me a sample of the "_properpair_sortchr_startend.bed" and the "_properpair_sortchr_startend.bg" files? It looks like you're creating them correctly, but I just want to verify. 

What options are you using to call SEACR (e.g. norm vs. non, AUC vs. union)? If I understand correctly, are you saying that you have yeast spike-in information but haven't utilized it? If you aren't using spike-in information, I'd recommend using "norm" to normalize. Alternatively, we typically normalize to a yeast spike-in by counting the number of reads _R_ that map to the yeast genome, and multiplying the fourth column of your bedgraph by 10000/_R_. Once you do that for both of your files, you can use "non" to avoid internal normalization and directly compare the spike-normalized TF and IgG files. Additionally, if it generally looks like you aren't getting enough peaks, "union" mode rather than "AUC" mode might help by including peaks that meet a max signal threshold even if they fail the total signal threshold.

Finally, what is the source of your IgG control file? I've found that I occasionally have issues with the quality of peaks called when the IgG is produced from a different biological replicate than the target CUT&RUN, or when the IgG is sequenced to a much different read depth than the target file.

Hope this helps!

Best,

Mike

**Comment by lb15** [comment]
Hi Mike,

Thanks for your response! Here's a random selection of lines from the files you mention (let me know if this suffices...I couldn't attach the .bed or .bg filetypes).
"_properpair_sortchr_startend.bed"
chr1    3000129 3000248
chr1    3000140 3000460
chr1    3000328 3000666
chr1    3000464 3000604
chr1    3000504 3000585
chr1    3000555 3000875
chr1    3000586 3000716
chr1    3000620 3000956
chr1    3000704 3000890
chr1    3001007 3001343
chr1    3001028 3001121
chr1    3001168 3001394
chr1    3001260 3001361

"_properpair_sortchr_startend.bg"
chr1    3000129 3000140 1
chr1    3000140 3000248 2
chr1    3000248 3000328 1
chr1    3000328 3000460 2
chr1    3000460 3000464 1
chr1    3000464 3000504 2
chr1    3000504 3000555 3
chr1    3000555 3000585 4
chr1    3000585 3000586 3
chr1    3000586 3000604 4
chr1    3000604 3000620 3
chr1    3000620 3000666 4
chr1    3000666 3000704 3
chr1    3000704 3000716 4
chr1    3000716 3000875 3
chr1    3000875 3000890 2
chr1    3000890 3000956 1
chr1    3001007 3001028 1

I tried two options: norm AUC and norm union. I don't see too many differences between the two runs - but I have only checked some of the major/known peaks via the genome browser. I'm getting the same number of regions in both output bed files: 98,852 while my MACS2 NarrowPeak file has 585 regions. It appears there are many false positives in both, but there are real MACS2 peaks that are absent in the SEACR files. And many of the peaks I see in the SEACR files don't correlate well with the original bams. 

 You are correct that I have spike-in information but haven't utilized it. That was why I included the "norm" parameter, as you mention. Thanks for the info on incorporating the yeast spike-in, I can try that to as an alternative normalization method.

The IgG control are the same cells, run in the same experiment with a rabbit IgG antibody instead of the GFP antibody (my TF is GFP tagged). My TF had a sequencing depth of 4.3 x 10^7 and the IgG was 2.7 x 10^7. I've been thinking that's comparable? Less than 2-fold difference?

For viewing the peaks, I have looked through the output bed file as well as converted it to a bigwig by including the 4th "score" column. I've been comparing to the NarrowPeaks file from MACS2 as well as the pileup file from MACS2. 

I'd be happy to share some more files or info offline if that's helpful.  Perhaps its how I'm visualizing the data, I'm new to this data type and still figuring out the different file types and visualization methods. 


Appreciate your help!

**Comment by mpmeers** [comment]
Hi Lauren,

Thanks for all the info. It appears the files are fine. Your peak calling results are surprising to me since for almost everything I've tested, SEACR is consistently more stringent than MACS2, whereas here it's dramatically the opposite. You said that you see false positives in both datasets though--how many peaks do you "expect" to get from this particular factor? 

One thing I do notice is that it appears you've sequenced to tremendous depth--47 million reads for your TF if I'm reading that correctly? In our [bioRxiv preprint](https://www.biorxiv.org/content/10.1101/569129v1), I show that, perhaps paradoxically, too many reads can be bad for SEACR. This is because it relies upon background that is sparse enough to derive a distribution of signal "in between the zeroes", so to speak, whereas sequencing to high depth may fill in those gaps and render you unable to derive a robust signal threshold for peak calling. One side-effect could be that lots of background areas appear to be strong enough to be called as peaks, resulting in a really high number. To address this possibility, one thing you might try is sub-sampling your paired-end fragment bed files down to ~10 million fragments each and trying again. My sense is that there might be some other issue here, but maybe that's somewhere to start. I'd be happy to confidentially receive files offline to dig in deeper if issues persist, but will keep this public for the time being for the benefit of other readers.

Mike

**Comment by lb15** [comment]
Hi Mike,

Thanks for your reply!

This TF has been notoriously difficult to get to work with ChIP-seq, so unfortunately, I don't have a good comparison to say how many total peaks I would expect. Papers for other members of this TF family have reported ~20,000 peaks with tiling arrays. I would not be surprised to see low levels of binding and perhaps fewer peaks than might be normally expected.

That's true about the sequencing depth, and a good suggestion. I do think there is overall high background in both the GFP and IgG. I will try sampling down to 10 million fragments and rerunning. I also am currently waiting on sequencing for a repeat run using the updated v2 Cut&Run protocol which I'm hopping can also help with the signal-to-noise. 

I'll let you know how the downsampling results look. 

Thanks again!

Lauren

**Comment by lb15** [comment]
Hi Mike,

While I have not completed the downsampling (got distracted by some other experiments), I did get the C&R v2 data back and run through SEACR. I'm not having the same problems as I did before and as described above. The peaks look reasonable and match well with MACS2. I'm going to close this since I think it was perhaps sample specific. Thanks for your advice and help!

Sincerely,
Lauren
